### PR TITLE
From Pr/3

### PR DESCRIPTION
**Pull request by g1eny0ung**
As title.

### CODE REVIEW

**Comment by g1eny0ung** [comment]
@FivePixels 

> Perfect usage in my opinion. Maybe if a week goes by since they previously opened the app, we should present them with this notification - if they've made, let's say an sixth of their goal since that week, congratulate them, otherwise, make a comment in it about continuing to work hard. I think this should have a toggle in the Settings, as personally it could frustrate the user (if they don't use it enough and are bombarded with a notification each time they decide to open it)

Now the notification function was just very basic. Will update base on this.~

**Comment by FivePixels** [comment]
This might take time to implement but I can't imagine it being too difficult. We can just add this to a project board for Features.

**Comment by g1eny0ung** [comment]
Yeap. I know you mean. The idea of **Update Frequency** was inspired by an app named [PopHub](http://questbe.at/pophub/), which is also a GitHub relevant application. And now the **update frequency** can be set as 2h, 6h, 12h, 24h. The numbers I set it up casually before. What about change it to
`12h, 24h, 2days, 5days, a week`? I think the contributions diff reminding in the notification center is a feature of GoalHub. So I want to keep it and decrease the frequency to avoid the annoying 😃.

The feature you mean I think we can add it in the future. I also agree with you. It's a good idea to encourage people. I strongly believe this feature was the **true meaning** of the desc I write **Trending your GitHub year contributions' goal**.

I will release a new version of all current changes and open a project to describe the new features.

Good job man! 🍺Also I'm going to take a vacation. Chinese new year is coming. I will back to work at 02.11.

As u say, the feature is not difficult. I'm the same as you think. The important thing I think is **how to** make this feature **emotionally**. We need a strategy.

**Comment by FivePixels** [comment]
Good to hear. I don't believe I have write access to the repository btw. Do you have a Telegram or a preferred way I can PM you about this project?

**Comment by g1eny0ung** [comment]
@FivePixels I have telegram but I almost never use it. I normally use WeChat. How can I add you to telegram or you add me in WeChat? My WeChat ID is yy0320yyy.

**Comment by FivePixels** [comment]
Sounds good. Would you be able to scan my code? I've never used WeChat. @g1eny0ung 
image

**Comment by g1eny0ung** [comment]
@FivePixels It says the QR code has expired. Need sign up again.

**Comment by g1eny0ung** [comment]
@FivePixels Expired again. 😢 I create a telegram username just now, it says someone can search me without the phone number. Same as my GitHub username. `g1eny0ung`

**Pull request merged**
